### ISSUE TITLE
Model not loading

### ISSUE THREAD

**Issue by shan75** [tevim/angular-stl-model-viewer#179]
Hi

Thank you for introducing this project as it is a long due.  Without this can't really implement three.js into angular. I am currently using Angular 8 app. All I am trying to do is to load a .stl file in the view.   As there is little or no documentation to say, Getting Started, I had lot of errors like missing module three and other three related modules. I have installed them all. 

<stl-model-viewer stlModel="./assets/modelfiles/123.stl" hasControls="true">
                                </stl-model-viewer>

All I am trying to do is this simple one line to view the model which is not working or throwing any errors.  Can you please give step by step implementation how to make it work?

Thank You

**Comment by KillerCodeMonkey** [comment]
@shan75 you know there is a live demo using this small compontent:
https://tevim.github.io/angular-stl-model-viewer/examples/basic/dist/my-app/

the code is also part of this repo, where you can see, how to integrate it in an angular cli project:
https://github.com/tevim/angular-stl-model-viewer/tree/master/examples/basic

**Comment by KillerCodeMonkey** [comment]
due to inactivity
