### ISSUE TITLE
Bullshit Library

### ISSUE THREAD

**Issue by assmabenmussa** [tevim/angular-stl-model-viewer#298]
Not only is your library not working. I went to check the example and the EXAMPLE isn't working!!!! Check your code before you publish your code.

**Comment by KillerCodeMonkey** [comment]
<img width="515" alt="Bildschirmfoto 2019-12-09 um 08 23 06" src="https://user-images.githubusercontent.com/2264672/70415616-50e9c600-1a5d-11ea-85dc-7faedab5ead4.png">

https://tevim.github.io/angular-stl-model-viewer/examples/basic/dist/my-app/
